[package]
name = "seekstorm"
version = "0.1.15"
authors = ["Wolf Garbe <wolf.garbe@seekstorm.com>"]
license = "Apache-2.0"
categories = ["database-implementations", "data-structures"]
description = """Search engine library & multi-tenancy server"""
documentation = "https://docs.rs/seekstorm/"
homepage = "https://seekstorm.com"
repository = "https://github.com/SeekStorm/SeekStorm"
readme = "README.md"
keywords = ["search", "information", "retrieval"]
edition = "2021"
exclude = ["assets/*",]

[lib]
name = "seekstorm"
path = "src/seekstorm/lib.rs"

[[bin]]
name = "seekstorm_server"
path = "src/seekstorm_server/main.rs"

[dependencies]
crossbeam-channel = "0.5.13"
ctrlc = "3.4.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
derivative = "2.2.0"
tokio = { version = "1.38.0", features = ["full"] }
base64 = "0.22.1"
num-format = "0.4.4"
ahash = "0.8.11"
rand = "0.8.5"
futures = "0.3.30"
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
regex = "1.10.5"
lazy_static = "1.5.0"
hyper = { version = "0.14.29", features = ["full"] }
url = "2.5.2"
sha2 = "0.10.8"
itertools = "0.13.0"
async-recursion = "1.1.1"
zstd = "0.13.1"
rayon = "1.10.0"
aho-corasick = "1.1.3"
smallvec = "1.13.2"
memmap2 = "0.9.4"
regex-syntax = "0.8.4"

[profile.release]
lto = true
opt-level = 3
debug = false
debug-assertions = false
panic = "abort"
overflow-checks = false
strip = "debuginfo"
